pod 'RongCloudIMKit'
pod 'KxMenu'
pod 'PopMenu'
pod 'JSAnimatedImagesView'
pod 'IHKeyboardAvoiding'
pod 'AJWValidator'
pod 'AVOSCloud'

source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
use_frameworks!

pod 'Alamofire', '~> 3.0'